In [ ]:
#Step 1 — Import libraries and set up paths

import pandas as pd
import numpy as np
from pathlib import Path

In [2]:

# Detect the project root
cwd = Path.cwd()

In [4]:
if cwd.name.lower() == "notebooks":
    PROJECT_ROOT = cwd.parent
else:
    PROJECT_ROOT = cwd

In [5]:
# Define paths
RAW_PATH = PROJECT_ROOT / "data" / "raw.csv"
CLEAN_DIR = PROJECT_ROOT / "data" / "cleaned"

In [6]:
# Create output directory
CLEAN_DIR.mkdir(parents=True, exist_ok=True)

In [7]:
# Verify paths
print("Project root:", PROJECT_ROOT)
print("Raw dataset exists:", RAW_PATH.exists())
print("Cleaned directory:", CLEAN_DIR)

Project root: d:\VS Code\Projects\python\Internship
Raw dataset exists: True
Cleaned directory: d:\VS Code\Projects\python\Internship\data\cleaned

In [ ]:
#Step 2 — Inspect the raw CSV before loading it

# Display the first five lines of the CSV
with open(RAW_PATH, "r", encoding="utf-8-sig") as file:
    for _ in range(5):
        line = file.readline()
        if not line:
            break
        print(line.rstrip())

    age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,zip_code
39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,93810
50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,24592
38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,13278
53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,46048

In [9]:
# Inspect the number of columns without assuming headers
preview = pd.read_csv(
    RAW_PATH,
    header=None,
    nrows=5,
    skipinitialspace=True
)

print("Number of columns:", preview.shape[1])
display(preview.head())

Number of columns: 16

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,zip_code
1,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,93810
2,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,24592
3,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,13278
4,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,46048

In [ ]:
#Step 3.1 — Load the dataset correctly

adult_columns = [
    "age",
    "workclass",
    "fnlwgt",
    "education",
    "education_num",
    "marital_status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "capital_gain",
    "capital_loss",
    "hours_per_week",
    "native_country",
    "income",
    "zip_code"
]

In [ ]:
#Step 3.2 — Load the dataset correctly

df = pd.read_csv(
    RAW_PATH,
    header=0,
    skipinitialspace=True,
    na_values=["?"],
    dtype={"zip_code": "string"}
)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

display(df.head())

Dataset loaded successfully!
Shape: (32561, 16)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,zip_code
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,93810
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,24592
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,13278
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,46048
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,42098

In [ ]:
#Step 4 — Inspect the dataset

print("Dataset dimensions:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
display(df.dtypes.to_frame("Data Type"))

print("\nMissing values per column:")
display(df.isna().sum().to_frame("Missing Values"))

print("\nDuplicate rows:", df.duplicated().sum())

print("\nIncome distribution:")
display(df["income"].value_counts(dropna=False).to_frame("Count"))

Dataset dimensions: (32561, 16)

Column names:
['age', 'workclass', 'fnlwgt', 'education', 'education_num', 'marital_status', 'occupation', 'relationship', 'race', 'sex', 'capital_gain', 'capital_loss', 'hours_per_week', 'native_country', 'income', 'zip_code']

Data types:

               Data Type
age                int64
workclass            str
fnlwgt             int64
education            str
education_num      int64
marital_status       str
occupation           str
relationship         str
race                 str
sex                  str
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country       str
income               str
zip_code          string

Missing values per column:

                Missing Values
age                          0
workclass                 1836
fnlwgt                       0
education                    0
education_num                0
marital_status               0
occupation                1843
relationship                 0
race                         0
sex                          0
capital_gain                 0
capital_loss                 0
hours_per_week               0
native_country             583
income                       0
zip_code                     0

Duplicate rows: 0

Income distribution:

        Count
income
<=50K   24720
>50K     7841

In [13]:
#Step 5 — Standardize column names and clean text values

# Standardize column names
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace("-", "_", regex=False)
    .str.replace(" ", "_", regex=False)
)

# Remove unnecessary whitespace from text columns
text_columns = df.select_dtypes(
    include=["object", "string"]
).columns

for col in text_columns:
    df[col] = df[col].str.strip()

# Convert remaining '?' markers into missing values
df = df.replace(r"^\s*\?\s*$", pd.NA, regex=True)

print("Column names standardized.")
print("Missing values after normalization:")
display(df.isna().sum().to_frame("Missing Values"))

Column names standardized.
Missing values after normalization:

                Missing Values
age                          0
workclass                 1836
fnlwgt                       0
education                    0
education_num                0
marital_status               0
occupation                1843
relationship                 0
race                         0
sex                          0
capital_gain                 0
capital_loss                 0
hours_per_week               0
native_country             583
income                       0
zip_code                     0

In [14]:
#Step 6 — Remove duplicate rows

rows_before = len(df)

df = df.drop_duplicates().reset_index(drop=True)

rows_removed = rows_before - len(df)

print("Rows before:", rows_before)
print("Duplicate rows removed:", rows_removed)
print("Rows after:", len(df))

Rows before: 32561
Duplicate rows removed: 0
Rows after: 32561

In [15]:
# Step 7 — Validate and save the cleaned dataset

# Validate expected columns
expected_columns = {
    "age", "workclass", "income", "zip_code"
}

assert expected_columns.issubset(df.columns)
assert not df.duplicated().any()

print("Validation passed.")
print("Final shape:", df.shape)
print("Target column:", "income")

# Save cleaned data
CLEAN_PATH = CLEAN_DIR / "adult_cleaned.csv"

df.to_csv(CLEAN_PATH, index=False)

print("Saved to:", CLEAN_PATH)

Validation passed.
Final shape: (32561, 16)
Target column: income
Saved to: d:\VS Code\Projects\python\Internship\data\cleaned\adult_cleaned.csv