In [1]:
# Load the cleaned dataset

import pandas as pd
from pathlib import Path

cwd = Path.cwd()
PROJECT_ROOT = cwd.parent if cwd.name.lower() == "notebooks" else cwd

DATA_PATH = PROJECT_ROOT / "data" / "cleaned" / "adult_cleaned.csv"

df = pd.read_csv(DATA_PATH, dtype={"zip_code": "string"})

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

display(df[["age", "zip_code"]].head())

Shape: (32561, 16)
Columns: ['age', 'workclass', 'fnlwgt', 'education', 'education_num', 'marital_status', 'occupation', 'relationship', 'race', 'sex', 'capital_gain', 'capital_loss', 'hours_per_week', 'native_country', 'income', 'zip_code']

   age zip_code
0   39    93810
1   50    24592
2   38    13278
3   53    46048
4   28    42098

In [2]:
import sys

sys.path.insert(0, str(PROJECT_ROOT))

from src.level1_encoding import (
    generalize_age,
    mask_zip_code,
    prepare_level1_features
)

sample = pd.DataFrame({
    "age": [23, 37, 48, 61, None],
    "zip_code": ["93810", "24592", "13278", "54321", None]
})

display(prepare_level1_features(sample))

     age zip_code
0  20-29    938**
1  30-39    245**
2  40-49    132**
3  60-69    543**
4   <NA>     <NA>

In [3]:
level1_df = prepare_level1_features(df)

print("Original age dtype:", df["age"].dtype)
print("Level 1 age dtype:", level1_df["age"].dtype)

print("Original ZIP dtype:", df["zip_code"].dtype)
print("Level 1 ZIP dtype:", level1_df["zip_code"].dtype)

display(level1_df[["age", "zip_code"]].head(10))

Original age dtype: int64
Level 1 age dtype: string
Original ZIP dtype: string
Level 1 ZIP dtype: string

     age zip_code
0  30-39    938**
1  50-59    245**
2  30-39    132**
3  50-59    460**
4  20-29    420**
5  30-39    392**
6  40-49    282**
7  50-59    234**
8  30-39    986**
9  40-49    814**