In [4]:

from pathlib import Path
import pandas as pd

# Find the project root
cwd = Path.cwd()
PROJECT_ROOT = (
    cwd.parent if cwd.name.lower() == "notebooks" else cwd
)

# Change this filename if Dhiraj used a different one
ANON_PATH = PROJECT_ROOT / "data" / "anonymized" / "level1" / "adult_level1.csv"

if not ANON_PATH.exists():
    raise FileNotFoundError(
        f"Dataset not found at: {ANON_PATH}\n"
        "Check the filename and folder location."
    )

df_level1 = pd.read_csv(
    ANON_PATH,
    skipinitialspace=True,
    dtype={"zip_code": "string"}
)

print("Dataset shape:", df_level1.shape)
print("\nColumn names:")
print(df_level1.columns.tolist())

print("\nData types:")
print(df_level1.dtypes)

print("\nMissing values:")
print(df_level1.isna().sum())

display(df_level1.head())

Dataset shape: (32561, 16)

Column names:
['age', 'workclass', 'fnlwgt', 'education', 'education_num', 'marital_status', 'occupation', 'relationship', 'race', 'sex', 'capital_gain', 'capital_loss', 'hours_per_week', 'native_country', 'income', 'zip_code']

Data types:
age                  str
workclass            str
fnlwgt             int64
education            str
education_num      int64
marital_status       str
occupation           str
relationship         str
race                 str
sex                  str
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country       str
income               str
zip_code          string
dtype: object

Missing values:
age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
zip_code             0
dtype: int64

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,zip_code
0,30-39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,938**
1,50-59,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,245**
2,30-39,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,132**
3,50-59,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,460**
4,20-29,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,420**

In [5]:

# Day 9 — Validate the Level 1 anonymized dataset

import pandas as pd

# 1. Check dataset size and column names
print("Dataset shape:", df_level1.shape)
print("\nColumns:")
print(df_level1.columns.tolist())

# 2. Check duplicate rows
print("\nDuplicate rows:", df_level1.duplicated().sum())

# 3. Check missing values
print("\nMissing values:")
print(df_level1.isna().sum())

# 4. Check age values
if "age" in df_level1.columns:
    print("\nAge examples:")
    print(df_level1["age"].value_counts(dropna=False).head(15))

# 5. Check ZIP masking
if "zip_code" in df_level1.columns:
    print("\nZIP code examples:")
    print(df_level1["zip_code"].value_counts(dropna=False).head(10))

# 6. Check target column
if "income" in df_level1.columns:
    print("\nIncome distribution:")
    print(df_level1["income"].value_counts(dropna=False))
else:
    print("\nWARNING: income target column is missing.")

Dataset shape: (32561, 16)

Columns:
['age', 'workclass', 'fnlwgt', 'education', 'education_num', 'marital_status', 'occupation', 'relationship', 'race', 'sex', 'capital_gain', 'capital_loss', 'hours_per_week', 'native_country', 'income', 'zip_code']

Duplicate rows: 0

Missing values:
age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
zip_code             0
dtype: int64

Age examples:
age
30-39    8613
20-29    8054
40-49    7175
50-59    4418
60-69    2015
10-19    1657
70-79     508
80-89      78
90-99      43
Name: count, dtype: int64

ZIP code examples:
zip_code
493**    59
542**    57
964**    54
218**    54
720**    53
850**    52
283**    51
285**    51
821**    50
231**    50
Name: count, dtype: int64[pyarrow]

Income distribution:
income
<=50K    24720
>50K      7841
Name: count, dtype: int64

In [6]:

# Day 9 — Normalize column names and inspect anonymization

df_level1.columns = df_level1.columns.str.strip()

print("Cleaned column names:")
print(df_level1.columns.tolist())

print("\nAge values:")
print(df_level1["age"].value_counts().head(15))

print("\nZIP code examples:")
print(df_level1["zip_code"].astype("string").head(15).tolist())

# Confirm required target exists
assert "income" in df_level1.columns, "Income target is missing"

print("\nIncome classes:")
print(df_level1["income"].value_counts())

print("\nColumn names and target check passed.")

Cleaned column names:
['age', 'workclass', 'fnlwgt', 'education', 'education_num', 'marital_status', 'occupation', 'relationship', 'race', 'sex', 'capital_gain', 'capital_loss', 'hours_per_week', 'native_country', 'income', 'zip_code']

Age values:
age
30-39    8613
20-29    8054
40-49    7175
50-59    4418
60-69    2015
10-19    1657
70-79     508
80-89      78
90-99      43
Name: count, dtype: int64

ZIP code examples:
['938**', '245**', '132**', '460**', '420**', '392**', '282**', '234**', '986**', '814**', '213**', '873**', '653**', '141**', '139**']

Income classes:
income
<=50K    24720
>50K      7841
Name: count, dtype: int64

Column names and target check passed.

In [7]:

# Day 9 — Final checks before pipeline testing

# 1. Inspect ZIP code masking
print("ZIP code examples:")
print(df_level1["zip_code"].astype("string").value_counts().head(15))

# 2. Check whether all ZIP values follow the expected masked format
zip_values = df_level1["zip_code"].astype("string").dropna()
zip_pattern_ok = zip_values.str.fullmatch(r"\d{3}\*\*", na=False)

print("\nZIP values matching the expected 3-digits + ** format:",
      zip_pattern_ok.sum(), "/", len(zip_values))

# 3. Check age groups
valid_age_groups = {
    f"{start}-{start + 9}" for start in range(0, 100, 10)
}
observed_age_groups = set(
    df_level1["age"].dropna().astype(str).unique()
)

print("\nUnexpected age groups:",
      sorted(observed_age_groups - valid_age_groups))

# 4. Check the target
print("\nMissing income values:", df_level1["income"].isna().sum())
print("Income labels:", df_level1["income"].unique())

# 5. Check final schema
print("\nFinal shape:", df_level1.shape)
print("Column names:", df_level1.columns.tolist())

ZIP code examples:
zip_code
493**    59
542**    57
964**    54
218**    54
720**    53
850**    52
283**    51
285**    51
821**    50
231**    50
332**    50
948**    50
464**    49
694**    49
800**    49
Name: count, dtype: int64[pyarrow]

ZIP values matching the expected 3-digits + ** format: 32561 / 32561

Unexpected age groups: []

Missing income values: 0
Income labels: <ArrowStringArray>
['<=50K', '>50K']
Length: 2, dtype: str

Final shape: (32561, 16)
Column names: ['age', 'workclass', 'fnlwgt', 'education', 'education_num', 'marital_status', 'occupation', 'relationship', 'race', 'sex', 'capital_gain', 'capital_loss', 'hours_per_week', 'native_country', 'income', 'zip_code']

In [8]:
# Prepare the data for model training

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

# Work on a copy; do not modify the source CSV
df_test = df_level1.copy()
df_test.columns = df_test.columns.str.strip()

# Separate target and features
X = df_test.drop(columns=["income"])
y = df_test["income"].astype(str).str.strip()

# Ensure generalized age and masked ZIP are categorical
X["age"] = X["age"].astype("string")
X["zip_code"] = X["zip_code"].astype("string")

# Identify numeric and categorical columns
numeric_features = X.select_dtypes(include=["number"]).columns.tolist()
categorical_features = X.select_dtypes(
    include=["object", "string", "category"]
).columns.tolist()

print("Numeric features:", numeric_features)
print("Categorical features:", categorical_features)

# Split using the same seed and ratio as the baseline
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Build preprocessing pipeline
numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", numeric_transformer, numeric_features),
    ("cat", categorical_transformer, categorical_features)
])

# Fit only on training data to avoid leakage
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print("\nTraining rows:", X_train_processed.shape[0])
print("Test rows:", X_test_processed.shape[0])
print("Processed training features:", X_train_processed.shape[1])
print("Processed test features:", X_test_processed.shape[1])

assert X_train_processed.shape[0] == len(y_train)
assert X_test_processed.shape[0] == len(y_test)

print("\nPreprocessing test passed.")

Numeric features: ['fnlwgt', 'education_num', 'capital_gain', 'capital_loss', 'hours_per_week']
Categorical features: ['age', 'workclass', 'education', 'marital_status', 'occupation', 'relationship', 'race', 'sex', 'native_country', 'zip_code']

Training rows: 26048
Test rows: 6513
Processed training features: 1013
Processed test features: 1013

Preprocessing test passed.

In [9]:
# Train both ML models


from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)
import pandas as pd

models = {
    "Logistic Regression": LogisticRegression(
        max_iter=1000,
        random_state=42
    ),
    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        random_state=42,
        n_jobs=-1
    )
}

level1_results = []

for model_name, model in models.items():
    print(f"Training {model_name}...")

    model.fit(X_train_processed, y_train)
    predictions = model.predict(X_test_processed)

    metrics = {
        "experiment": "Level 1",
        "model": model_name,
        "accuracy": accuracy_score(y_test, predictions),
        "precision": precision_score(
            y_test, predictions,
            pos_label=">50K", zero_division=0
        ),
        "recall": recall_score(
            y_test, predictions,
            pos_label=">50K", zero_division=0
        ),
        "f1_score": f1_score(
            y_test, predictions,
            pos_label=">50K", zero_division=0
        )
    }

    level1_results.append(metrics)
    print(f"Accuracy: {metrics['accuracy']:.4f}")
    print(f"Precision: {metrics['precision']:.4f}")
    print(f"Recall: {metrics['recall']:.4f}")
    print(f"F1-score: {metrics['f1_score']:.4f}")
    print("-" * 40)

level1_results_df = pd.DataFrame(level1_results)
display(level1_results_df)

Training Logistic Regression...
Accuracy: 0.8555
Precision: 0.7303
Recall: 0.6339
F1-score: 0.6787
----------------------------------------
Training Random Forest...
Accuracy: 0.8615
Precision: 0.7610
Recall: 0.6193
F1-score: 0.6828
----------------------------------------

  experiment                model  accuracy  precision    recall  f1_score
0    Level 1  Logistic Regression  0.855520   0.730345  0.633929  0.678730
1    Level 1        Random Forest  0.861508   0.760972  0.619260  0.682841

In [10]:
# Save  Level 1 results


from pathlib import Path

# Find project root
cwd = Path.cwd()
PROJECT_ROOT = cwd.parent if cwd.name.lower() == "notebooks" else cwd

RESULTS_DIR = PROJECT_ROOT / "results"
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

# Save Level 1 metrics
output_path = RESULTS_DIR / "level1_metrics.csv"
level1_results_df.to_csv(output_path, index=False)

print("Level 1 results saved to:", output_path)
display(pd.read_csv(output_path))

Level 1 results saved to: d:\VS Code\Projects\python\Internship\results\level1_metrics.csv

  experiment                model  accuracy  precision    recall  f1_score
0    Level 1  Logistic Regression  0.855520   0.730345  0.633929  0.678730
1    Level 1        Random Forest  0.861508   0.760972  0.619260  0.682841